### ISSUE TITLE
Segmentation fault [ros2run] 

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [ros-tooling/topic_tools#55]
## Description
Segmentation fault occurring when stopping the publisher and restarting while keeping the ros2 run topic throttle message active. 

In two separate terminals, publish two messages 
$ ros2 topic pub -r 10 /greetings std_msgs/msg/String "{data: 'Hello from terminal'}"
$ ros2 topic pub -r 10 /welcome std_msgs/msg/String "{data: 'Hello from terminal'}"

In two new terminals, run the commands, 
$ ros2 run topic_tools throttle messages /greetings 1
$ ros2 run topic_tools throttle messages /welcome 1

on doing a ros2 topic list, the following topics are visible:
/greetings
/greetings_throttle
/parameter_events
/rosout
/welcome
/welcome_throttle

Press control + c in terminal two (or in one) where the $ ros2 topic pub -r 10 /welcome std_msgs/msg/String "{data: 'Hello from terminal'}" was entered. 

and rerun the command again. 

### Expected Behavior
** clear and concise description of what you _expected_ to happen **

### Actual Behavior
** clear and concise description of what _actually_ happened. include copied logs whenever possible **
In the terminal where the following command was entered, $ ros2 run topic_tools throttle messages /welcome 
the following occurred. 
[ros2run]: Segmentation fault
 

## System (please complete the following information)
 - OS: Ubuntu 22.04
 - ROS 2 Distro: Humble

Is there any chance to keep the throttle active and connect again without segmentation fault when the topic starts to publish again?

Additional info
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.5', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/command/topic.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 89, in main
    return main(args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 104, in main
    _rostopic_hz(node.node, topic, window_size=args.window_size, filter_expr=filter_expr,
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 274, in _rostopic_hz
    rt.print_hz(topic)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/verb/hz.py", line 244, in print_hz
    print('average rate: %.3f\n\tmin: %.3fs max: %.3fs std dev: %.5fs window: %s'
BrokenPipeError: [Errno 32] Broken pipe

Thanks

**Comment by christophebedard** [comment]
I can reproduce. I'm using ROS 2 Rolling, but the `topic_tools` code is the same.

I'm looking into it.

**Comment by christophebedard** [comment]
This is a race. Here's what's happening:

* [`ToolBaseNode::make_subscribe_unsubscribe_decisions()`](https://github.com/ros-tooling/topic_tools/blob/623a01c4adce912fb27cdec9776eafc608a4c0d0/topic_tools/src/tool_base_node.cpp#L30) is called by a timer every 100 milliseconds
   * It checks if a publisher exists for the given input topic (e.g., `/greetings` or `/welcome`)
   * If a publisher exists, it creates a publisher for the output topic (e.g., `/greetings_throttle` or `/welcome_throttle`) and creates a subscription for the input topic (e.g., `/greetings` or `/welcome`)
   * If there is no publisher, it gets rid of the output topic publisher
      * Note that it does **not** get rid of its input topic subscription if no input topic publisher exists
* [`ThrottleNode::process_message()`](https://github.com/ros-tooling/topic_tools/blob/6a565052e927e80fe5e368ae42956f3961fa6a1d/topic_tools/src/throttle_node.cpp#L56) receives a new message from the input topic subscription
   * It publishes it (if the time difference since the last published message is greater than or equal to the throttle period, of course)

The segmentation fault happens when:

1. Run `ros2 topic pub -r 10 ...`: input publisher is created and publishes
2. Run `ros2 run topic_tools throttle ...`: throttle node is launched
   * Input topic publisher exists, so input subscription and output publisher are created
   * This is fine, since the subscription is created after the publisher, so the throttle node cannot receive any message and try to publish without a publisher
3. Kill `ros2 topic pub -r 10 ...`: throttle node's `ToolBaseNode::make_subscribe_unsubscribe_decisions()` method runs within 100 ms
   * The publisher is destroyed, but not the subscription
4. Re-run `ros2 topic pub -r 10 ...`: messages are published
5. Then two things can happen in the throttle node:
   1. Throttle node input subscription receives a message & the callback is called **before** `ToolBaseNode::make_subscribe_unsubscribe_decisions()` runs: it tries to publish using a bad publisher, which leads to a segmentation fault
      1. This happens most of the time
   2. `ToolBaseNode::make_subscribe_unsubscribe_decisions()` runs before the message is received & callback is called: the publisher is re-created
      1. When the subscription callback is eventually called, the publisher can successfully publish
      2. This happens rarely but it does happen

I see three potential solutions:

1. In the subscription callback (`ThrottleNode::process_message()`), do not publish (i.e., do not do anything) if the publisher doesn't exist
2. In the subscription callback (`ThrottleNode::process_message()`), create the publisher if needed
3. In `ToolBaseNode::make_subscribe_unsubscribe_decisions()`, if no input topic publishers exist, get rid of both the publisher and the subscription instead of only getting rid of the publisher
   * This way, the subscription callback does not get called while the publisher doesn't exist
   * When `ToolBaseNode::make_subscribe_unsubscribe_decisions()` is called after step 4 above, both the publisher and subscription will be re-created, and then the subscription callback will eventually be called and the publisher will successfully publish

Solutions 1 & 2 only affect `ThrottleNode`, while solution 3 potentially affects all `topic_tools` nodes, since they're based on `ToolBaseNode`. Solution 3 makes more sense to me, but I'm not sure how it would affect other nodes, and I'm not sure if there is a reason why the subscription is not destroyed when the publisher is destroyed.

Looking at recent PRs, this exact issue was fixed for the relay node by using solution 1, see #49. So we could probably do the same for the throttle node.

**Comment by christophebedard** [comment]
Here's a PR with a fix using solution 1: #56
